package explode2.labyrinth

enum class SearchCategory {
	HIDDEN, OFFICIAL, RANKED, UNRANKED, REVIEW, ALL
}

// Update 2026.6.2: added ASCENDING_BY_PUBLISH_TIME 
enum class SearchSort {
	DESCENDING_BY_PLAY_COUNT,
	DESCENDING_BY_PUBLISH_TIME,
	ASCENDING_BY_PUBLISH_TIME
}